books/urls.py
from django.urls import path
from .views import books_list, book_details, add_book_form, edit_book, AuthorAutocomplete

app_name = 'books'

urlpatterns = [
    path('<int:pk>', book_details, name='details'),
    path('', books_list, name='list'),
    path('add/', add_book_form, name='add'),
    path('<int:book_id>/edit', edit_book, name='edit'),
    path('author-autocomplete/', AuthorAutocomplete.as_view(), name='author-autocomplete'),
]

main/urls.py
from django.urls import path
from .views import index, about, contact, user_profile

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact', contact, name='contact'),
    path('user/<int:user_id>/profile', user_profile, name='userprofile')
]

posts/urls.py
from django.urls import path
from .views import posts_list, post_details,  add_post_form, edit_post

app_name = 'posts'


urlpatterns = [
    path('<int:pk>/', post_details, name='details'),
    path('', posts_list, name='list'),
    path('add/', add_post_form, name='add'),
    path('<int:post_id>/edit', edit_post, name='edit')
]

pywww_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('tags/', include('tags.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

register/urls.py
from django.urls import path
from .views import register

app_name = 'register'

urlpatterns = [
    path('', register, name='register')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        {% block style %}{% endblock %}
    </head>
    <body>
        <div class="container">
            <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
                 <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
                    <img src="{% static "main/img/logo.png" %}" alt="logo" height="50px">
                 </a>
                 <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
                     <li><a href="{% url "main:index" %}" class="nav-link px-2 link-secondary">Home</a></li>
                     <li><a href="{% url "posts:list" %}" class="nav-link px-2 link-dark">Posts</a></li>
                     <li><a href="{% url "books:list" %}" class="nav-link px-2 link-dark">Books</a></li>
                     <li><a href="{% url "main:about" %}" class="nav-link px-2 link-dark">About</a></li>
                     <li><a href="/admin/" class="nav-link px-2 link-dark">Admin</a></li>
                 </ul>
                 <div class="col-md-3 text-end">
                     {% if user.is_authenticated %}
                         <a type="button" class="btn btn-outline-primary me-2" href="{% url 'logout' %}">Logout</a>
                     {% else %}
                         <a type="button" class="btn btn-outline-primary me-2" href="{% url 'login' %}">Login</a>
                         <a type="button" class="btn btn-primary" href="{% url 'register:register' %}">Sign-up</a>
                     {% endif %}
                 </div>
            </header>

            {% block content %}{% endblock %}

             <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top" >
                 <p class="col-md-4 mb-0 text-muted" >&copy; 2021 Pywww, Inc </p>
                 <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none" >
                    <img src="{% static "main/img/logo.png" %}" alt="logo" width="30px">
                 </a>
                 <ul class="nav col-md-4 justify-content-end" >
                    <li class="nav-item" ><a href="{% url "main:about" %}" class="nav-link px-2 text-muted" >About</a></li>
                     <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link px-2 text-muted">Contact</a></li>
                 </ul>
             </footer>
        </div>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
        {% block additional_scripts %}{% endblock %}
    </body>
</html>