books/urls.py
from django.urls import path
from .views import books_list, book_details, add_book_form, edit_book, AuthorAutocomplete

app_name = 'books'

urlpatterns = [
    path('<int:pk>', book_details, name='details'),
    path('', books_list, name='list'),
    path('add/', add_book_form, name='add'),
    path('<int:book_id>/edit', edit_book, name='edit'),
    path('author-autocomplete/', AuthorAutocomplete.as_view(), name='author-autocomplete'),
]

main/urls.py
from django.urls import path
from .views import index, about, contact, user_profile

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact', contact, name='contact'),
    path('user/<int:user_id>/profile', user_profile, name='userprofile')
]

pywww_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('tags/', include('tags.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

books/models.py
from django.db import models
from common.models import Timestamped
from sorl.thumbnail import ImageField


class Author(Timestamped):
    name = models.CharField(max_length=255)
    birth_year = models.IntegerField()
    death_year = models.IntegerField(blank=True, null=True)
    biogram = models.TextField()

    def __str__(self):
        return f'{self.name}'


class Book(Timestamped):
    title = models.CharField(max_length=255)
    description = models.TextField()
    publication_year = models.IntegerField()
    available = models.BooleanField(default=False)
    tags = models.ManyToManyField('tags.Tag', related_name='books', blank=True)
    authors = models.ManyToManyField('Author', related_name='author')
    cover = ImageField(upload_to='books/covers/%Y/%m/%d', null=True, blank=True)

    def __str__(self):
        return f'{self.authors}: {self.title}'

books/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, ButtonHolder
from dal import autocomplete
from tags.models import Tag
from .models import Book, Author
from dal import autocomplete


class BookForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(url='tags:tag-autocomplete')
    )
    authors = forms.ModelMultipleChoiceField(
        queryset=Author.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(url='books:author-autocomplete')
    )

    class Meta:
        model = Book
        # fields = ['title', 'description', 'available', 'publication_year', 'authors', 'tags', 'cover']
        fields = "__all__"
        labels = {
            'title': 'Tytuł',
            'description': 'Opis',
            'available': 'Dostępność',
            'publication_year': 'Rok wydania',
            'authors': 'Autorzy',
            'tags': 'Tagi',
            'cover': 'Okładka'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        # self.helper.form_action = '?'
        self.helper.form_action = '?'
        self.helper.add_input(Submit('submit', 'Wyślij'))
        # self.helper.layout = Layout(
        #     Fieldset(
        #         'Dodawanie książki',
        #         'title',
        #         'authors',
        #         'description',
        #         'publication_year',
        #         'available',
        #         'tags',
        #         'cover'
        #     ),
        #     ButtonHolder(
        #         Submit('submit', 'Dodaj', css_class='btn btn-primary'),
        #         css_class='d-flex justify-content-end'
        #     )
        # )

books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Book, Author
from .forms import BookForm
from django.urls import reverse
from dal import autocomplete


def books_list(request):
    books = Book.objects.all()
    return render(request, 'books/books_list.html', {'books': books})


def book_details(request, pk):
    book = Book.objects.get(pk=pk)
    return render(request, 'books/book_details.html', {'book': book})


def add_book_form(request):
    if request.method == 'POST' and request.user.is_authenticated:
        form = BookForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()

            return HttpResponseRedirect(reverse('books:add'))
    else:
        form = BookForm()

    return render(request, 'books/add.html', {'form': form})


def edit_book(request, book_id):
    book = get_object_or_404(Book, pk=book_id)
    if request.method == 'POST' and request.user.is_authenticated:
        form = BookForm(request.POST, request.FILES, instance=book)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            form.save_m2m()
    else:
        form = BookForm(instance=book)

    return render(request, 'books/add.html', {'form': form})


class AuthorAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return Author.objects.none()

        qs = Author.objects.all()

        if self.q:
            qs = qs.filter(name__istartswith=self.q)

        return qs

books/templates/books/add.html
{% extends 'base.html' %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}Dodawanie książki{% endblock %}

{% block content %}

    {% crispy form form.helper %}

{% endblock %}

{% block additional_scripts %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ form.media }}
{% endblock %}

books/templates/books/book_details.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}{{ book.title }}{% endblock %}

{% block content %}
    <h1>{{ book.title }}</h1>
    <div class="row">
        <div class="col-md-6 text-center">
            {% if book.cover %}
                <img src="{{ book.cover.url }}" alt="cover" width="200">
            {% endif %}
        </div>
        <div class="col-md-6">
            <div>
                {% if book.available %}
                    <div class="alert alert-success" role="alert">Dostępna</div>
                {% else %}
                    <div class="alert alert-danger" role="alert">Wypożyczona</div>
                {% endif %}
            </div>
        </div>

        {% if book.authors.all|length == 1 %}
            <div>Autor: {{ book.authors.first }}</div>
        {% else %}
            <div>Autorzy:</div>
            {% for author in book.authors.all %}
                {{ author.name }}<br>
            {% endfor %}
        {% endif %}


        <div>Rok wydania: {{ book.publication_year }}</div>
        <div>Opis:</div>
        <div>{{ book.description }}</div>

    </div>
{% endblock %}

books/templates/books/books_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Lista książek{% endblock %}

{% block content %}
    <h1 class="card-title">Lista książek</h1>
        <ul class="list-group">
            {% for book in books %}
                <a class="list-group-item" href="{% url 'books:details' book.id %}">{{ book.title }}{% if book.available %}(na półce){% else %}(wypożyczona){% endif %} </a>
            {% endfor %}
        </ul>
{% endblock %}

books/templates/books/borrows_list.html
{% extends 'base.html' %}

{% block title %}Wypożyczenia{% endblock %}

{% block content %}

    <table class="table table-striped">
        <thead><th>Tytuł</th><th>Data wypożyczenia</th><th>Data zwrotu</th></thead>
        <tbody>
        {% for borrow in borrows %}
            <form action="{% url 'books:borrows_list' %}" method="post">
            {% csrf_token %}
            <tr><td>{{ borrow.book.title }}</td><td>{{ borrow.borrow_date }}</td>
                <td>{% if borrow.return_date %}{{ borrow.return_date }}{% else %}
                    <button type="submit" name="book_{{ borrow.book.id }}" class="btn btn-primary">Zwróć</button>
                {% endif %}
                </td>
            </tr>
            </form>
        {% endfor %}
        </tbody>
    </table>

{% endblock %}