main/urls.py
from django.urls import path
from .views import index, about, contact, user_profile

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact', contact, name='contact'),
    path('user/<int:user_id>/profile', user_profile, name='userprofile')
]

posts/urls.py
from django.urls import path
from .views import posts_list, post_details,  add_post_form, edit_post

app_name = 'posts'


urlpatterns = [
    path('<int:pk>/', post_details, name='details'),
    path('', posts_list, name='list'),
    path('add/', add_post_form, name='add'),
    path('<int:post_id>/edit', edit_post, name='edit')
]

pywww_new/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('books/', include('books.urls')),
    path('posts/', include('posts.urls')),
    path('tags/', include('tags.urls')),
    path('register/', include('register.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from common.models import Timestamped
from datetime import datetime
from sorl.thumbnail import ImageField


class Post(Timestamped):
    title = models.CharField(verbose_name='Tytuł', max_length=255)
    content = models.TextField(verbose_name='Treść')
    published = models.BooleanField(verbose_name='Opublikowany', default=False)
    sponsored = models.BooleanField(verbose_name='Sponsorowany', default=False)
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    tags = models.ManyToManyField('tags.Tag', related_name='posts')
    example_file = models.FileField(upload_to='posts/examples/', blank=True, null=True)
    image_width = models.IntegerField(blank=True, null=True, editable=False)
    image = ImageField(upload_to='posts/images/%Y/%m/%d', null=True, width_field='image_width')

    def __str__(self):
        return f'{self.id}: {self.title} '

posts/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Fieldset, HTML, ButtonHolder
from django.contrib.admin.widgets import AutocompleteSelectMultiple
from django.contrib import admin
from tags.models import Tag
from .models import Post
from dal import autocomplete


class PostForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=autocomplete.ModelSelect2Multiple(url='tags:tag-autocomplete')
        # widget=AutocompleteSelectMultiple(
        #     Post._meta.get_field('tags'),
        #     admin.AdminSite()
        # )
    )

    class Meta:
        model = Post
        fields = ['title', 'content', 'sponsored', 'published', 'image', 'tags']
        labels = {
            'title': 'Tytuł',
            'content': 'Treść',
            'sponsored': 'Sponsorowany',
            'published': 'Opublikowany',
            'image': 'Obraz',
            'tags': 'Tagi'
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = '?'
        self.helper.layout = Layout(
            Fieldset(
                'Dodawanie postu',
                'title',
                'content',
                'sponsored',
                'published',
                'image',
                'tags'
            ),
            ButtonHolder(
                Submit('submit', 'Dodaj', css_class='btn btn-primary'),
                css_class='d-flex justify-content-end'
            )
        )

posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from .forms import PostForm
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.paginator import Paginator


def posts_list(request):
    posts = Post.objects.filter(published=True)
    q = request.GET.get('q')

    if q:
        posts = posts.filter(title__icontains=q)

    paginator = Paginator(posts, 10)
    page_number = request.GET.get('page')
    posts_lis = paginator.get_page(page_number)
    return render(request, 'posts/list.html', {'posts_lis': posts_lis})


def post_details(request, pk):
    post = Post.objects.get(pk=pk)
    context = {}
    if post.published:
        context['post'] = post
    return render(request, 'posts/details.html', context)


def add_post_form(request):
    if request.method == 'POST' and request.user.is_authenticated:
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()

            return HttpResponseRedirect(reverse('posts:add'))
    else:
        form = PostForm()

    return render(request, 'posts/add.html', {'form': form})


def edit_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST' and request.user.is_authenticated:
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            form.save_m2m()
    else:
        form = PostForm(instance=post)

    return render(request, 'posts/add.html', {'form': form})

posts/templates/posts/add.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% load static %}

{% block title %}Dodawanie posta{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/css/style.css' %}">
{% endblock %}

{% block content %}

    {% crispy form form.helper %}

{#    <h1>Dodanie nowego posta</h1>#}
{#    <form method="POST" class="form-label">#}
{#        {% csrf_token %}#}
{#        <p>#}
{#            <input type="text" class="form-control" name="title" id="id_title" required placeholder="Tytuł">#}
{#        </p>#}
{#        <p>#}
{#            <textarea class="form-control" name="content" id="id_content" cols="90" rows="5" required placeholder="Treść"></textarea>#}
{#        </p>#}
{#        <p>#}
{#            <input type="checkbox" class="form-check-input" id="id_published">#}
{#            <label class="form-check-label" for="id_published">Opublikowany</label>#}
{#        </p>#}
{#        <p>#}
{#            <input type="checkbox" class="form-check-input" id="id_sponsored">#}
{#            <label class="form-check-label" for="id_sponsored">Sponsorowany</label>#}
{#        </p>#}
{#        <p>#}
{#            <input class="form-control" type="file" name="example_file" id="id_example_file"><br>#}
{#        </p>#}
{#        <p>#}
{#            <input class="form-control" type="file" name="image" id="id_image" accept="image/*"><br>#}
{#        </p>#}
{#            <input type="submit" class="btn btn-primary" value="Dodaj">#}
{#    </form>#}
{##}


{% endblock %}

{% block additional_scripts %}
    <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
    {{ form.media }}
{% endblock %}

posts/templates/posts/details.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Szczegóły posta{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'posts/css/style.css' %}">
{% endblock %}

{% block content %}
        <h2>{{ post.title }}</h2>
        <div>
            {% if post %}
                <small>Utworzono {{ post.created }}, zmodyfikowano {{ post.modified }}</small>
            {% else %}
                <h1>Ten post nie jest opublikowany</h1>
            {% endif %}
        </div>
        <div>
            <p>{{ post.content }}</p>
        </div>
        {% if post.example_file %}
            <div>Pobierz <a href="{{ post.example_file.url }}">przykład</a></div>
        {% endif %}
        {% if post.image %}
            <div>
                <img src="{{ post.image.url }}" class="img-thumbnail" alt="image">
            </div>
        {% endif %}
        <a href="{% url "posts:edit" post.id %}" class="btn btn-primary">Edycja</a>
{% endblock %}

posts/templates/posts/list.html
{% extends 'base.html' %}

{% load static %}

{% load posts_extras %}

{% block title %}Lista postów{% endblock %}

{% block style %}
    <link rel="stylesheet" href="{% static 'posts/css/style.css' %}">
{% endblock %}

{% block content %}
    <div class="row">
        <form>
            <input type="text" id="q" name="q">
            <input type="submit" value="search">
        </form>
    </div>

    <h1 class="title">Lista postów</h1>
    <ul class="list-group">
        {% for post in posts_lis %}

            <a class="list-group-item" href="{% url 'posts:details' post.id %}">
                {{ post }}{% if post.sponsored %} (sponsorowany) {% endif %}
            </a>

        {% endfor %}
    </ul>

    <ul class="pagination justify-content-center">

        {% if posts_lis.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts_lis.previous_page_number }}">
                    <<
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span>
                    <i class="fa fa-chevron-left" aria-hidden="true"></i>
                </span>
            </li>
        {% endif %}

        {% if posts_lis.number|add:'-4' > 1 %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts_lis.number|add:'-5' }}">&hellip;</a>
            </li>
        {% endif %}

        {% for i in posts_lis.paginator.page_range %}
            {% if posts_lis.number == i %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">
                        {{ i }}
                        <span class="sr-only">
                            (current)
                        </span>
                    </span>
                </li>
            {% elif i > posts_lis.number|add:'-5' and i < posts_lis.number|add:'5' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ i }}">
                        {{ i }}
                    </a>
                </li>
            {% endif %}
        {% endfor %}

        {% if posts_lis.paginator.num_pages > posts_lis.number|add:'4' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts_lis.number|add:'5' }}">&hellip;</a>
            </li>
        {% endif %}

        {% if posts_lis.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts_lis.next_page_number }}">
                    >>
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <span>
                    <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </span>
            </li>
        {% endif %}

    </ul>


    {#        <nav aria-label="Page navigation">#}
    {#            <ul class="pagination justify-content-center">#}
    {#                {% if posts_lis.has_previous %}#}
    {#                    <li class="page-item">#}
    {#                        <a class="page-link" href="?page={{ posts_lis.previous_page_number }}" aria-label="<">#}
    {#                            <span aria-hidden="true">&laquo;</span>#}
    {#                            <span class="sr-only">begin</span>#}
    {#                        </a>#}
    {#                    </li>#}
    {#                {% endif %}#}
    {##}
    {#                {% for i in posts_lis.paginator.page_range %}#}
    {#                    {% if posts_lis.number == i %}#}
    {#                        <li class="page-item active">#}
    {#                            <span class="page-link">#}
    {#                                {{ i }}#}
    {#                                <span class="sr-only">(current)</span>#}
    {#                            </span>#}
    {#                        </li>#}
    {#                    {% elif i > posts_lis.number|add:'-3' and n < posts_lis.number|add:'3' %}#}
    {#                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>#}
    {#                    {% endif %}#}
    {#                {% endfor %}#}
    {##}
    {#                {% if posts_lis.has_next %}#}
    {#                    <li class="page-item">#}
    {#                        <a class="page-link" href="?page={{ posts_lis.paginator.num_pages }}" aria-label=">">#}
    {#                            <span aria-hidden="true">&raquo;</span>#}
    {#                            <span class="sr-only">end</span>#}
    {#                        </a>#}
    {#                    </li>#}
    {#                {% endif %}#}
    {##}
    {#            </ul>#}
    {##}
    {#        </nav>#}



    {#        <div class="pagination">#}
    {#            <span class="step-links">#}
    {#                {% if posts_lis.has_previous %}#}
    {#                    <a href="?page=1">&laquo; Pierwsza</a>#}
    {#                    <a href="?page={{ posts_lis.previous_page_number }}">Poprzednia</a>#}
    {#                {% endif %}#}
    {#                <span class="current">#}
    {#                    Page {{ posts_lis.number }} of {{ posts_lis.paginator.num_pages }}.#}
    {#                </span>#}
    {##}
    {#                {% if posts_lis.has_next %}#}
    {#                    <a href="?page={{ posts_lis.next_page_number }}">Następna</a>#}
    {#                    <a href="?page={{ posts_lis.paginator.num_pages }}">Ostatnia &raquo;</a>#}
    {#                {% endif %}#}
    {#            </span>#}
    {#        </div>#}
{% endblock %}